title: Dario Sidhu
logo: /assets/img/logo.png
description:
    PhD Student, Political Science
    University of California, Los Angeles (UCLA)
    dariosidhu@ucla.edu
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
