title: Dario Sidhu
logo: /assets/img/logo.png
description: |
  PhD Student, Political Science
  University of California, Los Angeles
  dariosidhu@ucla.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
